---
repos:
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.23
  hooks:
    - id: terragrunt-hclfmt
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.88.4
  hooks:
    - id: terraform_fmt
      args:
        - --args=-no-color
        - --args=-diff
        - --args=-write=false
        - --args=-recursive
    - id: terragrunt_validate
    - id: terraform_validate
      args:
        - --args=-json
        - --hook-config=--retry-once-with-cleanup=true
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-yaml
